# Generated by Django 4.1.7 on 2023-03-21 14:16

import account.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, validators=[account.validators.validate_pattern, django.core.validators.MinLengthValidator(8, '請至少輸入8個字母')])),
                ('password', models.CharField(max_length=32, validators=[account.validators.validate_pattern, django.core.validators.MinLengthValidator(8, '請至少輸入8個字母')])),
            ],
        ),
    ]
